name = "USA"
image = "pg-usa.jpeg"
regions = [
    "region 3",
    "region 4",
    "region 5",
    "region 6",
    "region 7",
    "region 1",
    "region 2",
]

[[cities]]
id = "portland"
name = "Portland"
region = "region 5"
x = 0.04055386409163475
y = 0.3155205249786377

[[cities]]
id = "sanfrancisco"
name = "San Francisco"
region = "region 5"
x = 0.03012055717408657
y = 0.4602698087692261

[[connections]]
from = "portland"
to = "sanfrancisco"
cost = 20
