name = "USA"
image = "pg-usa.jpeg"
regions = [
    "northwest",
    "west",
    "southwest",
    "central",
    "south",
    "east",
    "northeast",
]

[[cities]]
id = "seattle"
name = "Seattle"
region = "northwest"
x = 0.04249999299645424
y = 0.2434825599193573

[[cities]]
id = "vancouver"
name = "Vancouver"
region = "northwest"
x = 0.04200582206249237
y = 0.16544243693351746

[[cities]]
id = "portland"
name = "Portland"
region = "west"
x = 0.04154215380549431
y = 0.3151930272579193

[[cities]]
id = "regina"
name = "Regina"
region = "northwest"
x = 0.2824314534664154
y = 0.17033566534519196

[[cities]]
id = "calgary"
name = "Calgary"
region = "northwest"
x = 0.12405134737491608
y = 0.10149067640304565

[[cities]]
id = "billings"
name = "Billings"
region = "northwest"
x = 0.17089395225048065
y = 0.035077013075351715

[[cities]]
id = "winnipeg"
name = "Winnipeg"
region = "northwest"
x = 0.43014228343963623
y = 0.1735837459564209

[[cities]]
id = "minneapolis"
name = "Minneapolis"
region = "northwest"
x = 0.4723767638206482
y = 0.3105389475822449

[[cities]]
id = "sanfrancisco"
name = "San Francisco"
region = "west"
x = 0.03012000024318695
y = 0.4602699875831604

[[cities]]
id = "losangeles"
name = "Los Angeles"
region = "west"
x = 0.058811575174331665
y = 0.5979996919631958

[[cities]]
id = "sandiego"
name = "San Diego"
region = "west"
x = 0.10601163655519485
y = 0.6632616519927979

[[cities]]
id = "lasvegas"
name = "Las Vegas"
region = "west"
x = 0.15559999644756317
y = 0.48919999599456787

[[cities]]
id = "saltlakecity"
name = "Salt Lake City"
region = "west"
x = 0.19873648881912231
y = 0.3839681148529053

[[cities]]
id = "phoenix"
name = "Phoenix"
region = "southwest"
x = 0.2638274133205414
y = 0.6839585304260254

[[cities]]
id = "tucson"
name = "Tucson"
region = "southwest"
x = 0.2808554768562317
y = 0.7848890423774719

[[cities]]
id = "elpaso"
name = "El Paso"
region = "southwest"
x = 0.3679329752922058
y = 0.9157087206840515

[[cities]]
id = "albuquerque"
name = "Albuquerque"
region = "southwest"
x = 0.268960565328598
y = 0.6089596152305603

[[cities]]
id = "amarillo"
name = "Amarillo"
region = "southwest"
x = 0.4741421341896057
y = 0.9279488325119019

[[cities]]
id = "sanantonio"
name = "San Antonio"
region = "southwest"
x = 0.47432345151901245
y = 0.9631435871124268

[[cities]]
id = "dallas"
name = "Dallas"
region = "southwest"
x = 0.39887166023254395
y = 0.839459240436554

[[cities]]
id = "denver"
name = "Denver"
region = "west"
x = 0.2803916037082672
y = 0.44997644424438477

[[cities]]
id = "cheyenne"
name = "Cheyenne"
region = "central"
x = 0.4258301854133606
y = 0.40300989151000977

[[cities]]
id = "omaha"
name = "Omaha"
region = "central"
x = 0.451200008392334
y = 0.39410001039505005

[[cities]]
id = "desmoines"
name = "Des Moines"
region = "central"
x = 0.4878000020980835
y = 0.387800008058548

[[cities]]
id = "kansascity"
name = "Kansas City"
region = "central"
x = 0.44534391164779663
y = 0.47079652547836304

[[cities]]
id = "wichita"
name = "Wichita"
region = "central"
x = 0.38357242941856384
y = 0.43006810545921326

[[cities]]
id = "oklahomacity"
name = "Oklahoma City"
region = "central"
x = 0.4268546998500824
y = 0.5887960195541382

[[cities]]
id = "stlouis"
name = "St. Louis"
region = "central"
x = 0.5357940196990967
y = 0.5006585717201233

[[cities]]
id = "houston"
name = "Houston"
region = "south"
x = 0.4838770627975464
y = 0.7121342420578003

[[cities]]
id = "neworleans"
name = "New Orleans"
region = "south"
x = 0.5900448560714722
y = 0.7182308435440063

[[cities]]
id = "memphis"
name = "Memphis"
region = "south"
x = 0.415470689535141
y = 0.7741481065750122

[[cities]]
id = "nashville"
name = "Nashville"
region = "south"
x = 0.4499472677707672
y = 0.6555650234222412

[[cities]]
id = "louisville"
name = "Louisville"
region = "south"
x = 0.5584193468093872
y = 0.539621114730835

[[cities]]
id = "birmingham"
name = "Birmingham"
region = "south"
x = 0.6200283765792847
y = 0.5996562242507935

[[cities]]
id = "atlanta"
name = "Atlanta"
region = "south"
x = 0.6863847374916077
y = 0.6544259190559387

[[cities]]
id = "jacksonville"
name = "Jacksonville"
region = "south"
x = 0.7175719141960144
y = 0.7321897149085999

[[cities]]
id = "tampa"
name = "Tampa"
region = "south"
x = 0.6228166818618774
y = 0.8021310567855835

[[cities]]
id = "miami"
name = "Miami"
region = "south"
x = 0.725279688835144
y = 0.8096402287483215

[[cities]]
id = "chicago"
name = "Chicago"
region = "east"
x = 0.5940790176391602
y = 0.39027321338653564

[[cities]]
id = "detroit"
name = "Detroit"
region = "east"
x = 0.7225696444511414
y = 0.383143812417984

[[cities]]
id = "cleveland"
name = "Cleveland"
region = "east"
x = 0.7449343800544739
y = 0.41147956252098083

[[cities]]
id = "pittsburgh"
name = "Pittsburgh"
region = "east"
x = 0.7766643762588501
y = 0.42811012268066406

[[cities]]
id = "cincinnati"
name = "Cincinnati"
region = "east"
x = 0.6846186518669128
y = 0.5257700681686401

[[cities]]
id = "columbus"
name = "Columbus"
region = "east"
x = 0.715815007686615
y = 0.4765254259109497

[[cities]]
id = "indianapolis"
name = "Indianapolis"
region = "east"
x = 0.6184796690940857
y = 0.4507424831390381

[[cities]]
id = "philadelphia"
name = "Philadelphia"
region = "east"
x = 0.8667015433311462
y = 0.48238471150398254

[[cities]]
id = "baltimore"
name = "Baltimore"
region = "east"
x = 0.7936612367630005
y = 0.4808591306209564

[[cities]]
id = "washington"
name = "Washington"
region = "east"
x = 0.7975702881813049
y = 0.5290979146957397

[[cities]]
id = "newyork"
name = "New York"
region = "northeast"
x = 0.8791603446006775
y = 0.4206883907318115

[[cities]]
id = "albany"
name = "Albany"
region = "northeast"
x = 0.7928000092506409
y = 0.3677999973297119

[[cities]]
id = "hartford"
name = "Hartford"
region = "northeast"
x = 0.830694854259491
y = 0.391086220741272

[[cities]]
id = "providence"
name = "Providence"
region = "northeast"
x = 0.8644134402275085
y = 0.35925498604774475

[[cities]]
id = "boston"
name = "Boston"
region = "northeast"
x = 0.9625676274299622
y = 0.3719552159309387

[[cities]]
id = "portlandme"
name = "Portland (ME)"
region = "northeast"
x = 0.906289279460907
y = 0.27890095114707947

[[cities]]
id = "burlington"
name = "Burlington"
region = "northeast"
x = 0.8348034620285034
y = 0.3093223571777344

[[connections]]
from = "seattle"
to = "vancouver"
cost = 4

[[connections]]
from = "seattle"
to = "portland"
cost = 5

[[connections]]
from = "vancouver"
to = "regina"
cost = 28

[[connections]]
from = "vancouver"
to = "calgary"
cost = 16

[[connections]]
from = "regina"
to = "calgary"
cost = 14

[[connections]]
from = "calgary"
to = "billings"
cost = 5

[[connections]]
from = "winnipeg"
to = "minneapolis"
cost = 7

[[connections]]
from = "portland"
to = "sanfrancisco"
cost = 20

[[connections]]
from = "regina"
to = "saltlakecity"
cost = 29

[[connections]]
from = "minneapolis"
to = "chicago"
cost = 15

[[connections]]
from = "minneapolis"
to = "desmoines"
cost = 12

[[connections]]
from = "winnipeg"
to = "omaha"
cost = 20

[[connections]]
from = "sanfrancisco"
to = "losangeles"
cost = 12

[[connections]]
from = "losangeles"
to = "sandiego"
cost = 3

[[connections]]
from = "losangeles"
to = "lasvegas"
cost = 8

[[connections]]
from = "lasvegas"
to = "saltlakecity"
cost = 14

[[connections]]
from = "lasvegas"
to = "phoenix"
cost = 15

[[connections]]
from = "saltlakecity"
to = "denver"
cost = 14

[[connections]]
from = "phoenix"
to = "tucson"
cost = 4

[[connections]]
from = "phoenix"
to = "albuquerque"
cost = 14

[[connections]]
from = "phoenix"
to = "elpaso"
cost = 22

[[connections]]
from = "tucson"
to = "elpaso"
cost = 8

[[connections]]
from = "elpaso"
to = "albuquerque"
cost = 10

[[connections]]
from = "elpaso"
to = "sanantonio"
cost = 22

[[connections]]
from = "albuquerque"
to = "amarillo"
cost = 8

[[connections]]
from = "amarillo"
to = "dallas"
cost = 10

[[connections]]
from = "dallas"
to = "sanantonio"
cost = 7

[[connections]]
from = "sanantonio"
to = "houston"
cost = 7

[[connections]]
from = "dallas"
to = "houston"
cost = 8

[[connections]]
from = "amarillo"
to = "oklahomacity"
cost = 8

[[connections]]
from = "dallas"
to = "oklahomacity"
cost = 5

[[connections]]
from = "houston"
to = "neworleans"
cost = 12

[[connections]]
from = "cheyenne"
to = "denver"
cost = 4

[[connections]]
from = "denver"
to = "albuquerque"
cost = 20

[[connections]]
from = "denver"
to = "kansascity"
cost = 20

[[connections]]
from = "denver"
to = "wichita"
cost = 18

[[connections]]
from = "cheyenne"
to = "omaha"
cost = 15

[[connections]]
from = "omaha"
to = "desmoines"
cost = 5

[[connections]]
from = "omaha"
to = "kansascity"
cost = 7

[[connections]]
from = "desmoines"
to = "kansascity"
cost = 10

[[connections]]
from = "kansascity"
to = "stlouis"
cost = 8

[[connections]]
from = "kansascity"
to = "wichita"
cost = 5

[[connections]]
from = "kansascity"
to = "oklahomacity"
cost = 10

[[connections]]
from = "wichita"
to = "oklahomacity"
cost = 5

[[connections]]
from = "stlouis"
to = "chicago"
cost = 11

[[connections]]
from = "stlouis"
to = "nashville"
cost = 12

[[connections]]
from = "stlouis"
to = "memphis"
cost = 7

[[connections]]
from = "stlouis"
to = "louisville"
cost = 10

[[connections]]
from = "stlouis"
to = "indianapolis"
cost = 9

[[connections]]
from = "desmoines"
to = "chicago"
cost = 10

[[connections]]
from = "neworleans"
to = "memphis"
cost = 10

[[connections]]
from = "neworleans"
to = "birmingham"
cost = 10

[[connections]]
from = "memphis"
to = "nashville"
cost = 8

[[connections]]
from = "memphis"
to = "birmingham"
cost = 8

[[connections]]
from = "nashville"
to = "louisville"
cost = 5

[[connections]]
from = "nashville"
to = "birmingham"
cost = 7

[[connections]]
from = "nashville"
to = "atlanta"
cost = 8

[[connections]]
from = "nashville"
to = "cincinnati"
cost = 9

[[connections]]
from = "louisville"
to = "cincinnati"
cost = 4

[[connections]]
from = "louisville"
to = "indianapolis"
cost = 5

[[connections]]
from = "birmingham"
to = "atlanta"
cost = 4

[[connections]]
from = "atlanta"
to = "jacksonville"
cost = 10

[[connections]]
from = "jacksonville"
to = "tampa"
cost = 8

[[connections]]
from = "jacksonville"
to = "miami"
cost = 15

[[connections]]
from = "tampa"
to = "miami"
cost = 7

[[connections]]
from = "chicago"
to = "detroit"
cost = 7

[[connections]]
from = "chicago"
to = "indianapolis"
cost = 7

[[connections]]
from = "detroit"
to = "cleveland"
cost = 5

[[connections]]
from = "detroit"
to = "columbus"
cost = 7

[[connections]]
from = "cleveland"
to = "pittsburgh"
cost = 5

[[connections]]
from = "cleveland"
to = "columbus"
cost = 5

[[connections]]
from = "pittsburgh"
to = "columbus"
cost = 7

[[connections]]
from = "pittsburgh"
to = "philadelphia"
cost = 10

[[connections]]
from = "pittsburgh"
to = "baltimore"
cost = 8

[[connections]]
from = "columbus"
to = "cincinnati"
cost = 4

[[connections]]
from = "columbus"
to = "indianapolis"
cost = 7

[[connections]]
from = "cincinnati"
to = "indianapolis"
cost = 5

[[connections]]
from = "philadelphia"
to = "baltimore"
cost = 5

[[connections]]
from = "philadelphia"
to = "washington"
cost = 5

[[connections]]
from = "baltimore"
to = "washington"
cost = 4

[[connections]]
from = "philadelphia"
to = "newyork"
cost = 5

[[connections]]
from = "pittsburgh"
to = "newyork"
cost = 18

[[connections]]
from = "newyork"
to = "albany"
cost = 5

[[connections]]
from = "newyork"
to = "hartford"
cost = 4

[[connections]]
from = "albany"
to = "burlington"
cost = 8

[[connections]]
from = "albany"
to = "hartford"
cost = 5

[[connections]]
from = "hartford"
to = "providence"
cost = 3

[[connections]]
from = "hartford"
to = "boston"
cost = 5

[[connections]]
from = "providence"
to = "boston"
cost = 4

[[connections]]
from = "boston"
to = "portlandme"
cost = 7

[[connections]]
from = "burlington"
to = "portlandme"
cost = 10

[[connections]]
from = "billings"
to = "regina"
cost = 15

[[connections]]
from = "portland"
to = "saltlakecity"
cost = 22

[[connections]]
from = "saltlakecity"
to = "sanfrancisco"
cost = 22

[[connections]]
from = "sanfrancisco"
to = "lasvegas"
cost = 16

[[connections]]
from = "lasvegas"
to = "denver"
cost = 25
